### ISSUE TITLE
Support for Edm.DateTime in KeyPredicate

### ISSUE THREAD

**Issue by tdespres** [Soontao/light-odata#418]
Hello @Soontao,

I need to perform requests (GET, PATCH, DELETE) on entities that have datetimes in the key predicate :
`/Entity(StartDate=datetime'2022-01-01T00%3A00%3A00',EndDate=datetime'2022-12-31T00%3A00%3A00')`

And Date values are not supported in the formatIdString function :
https://github.com/Soontao/light-odata/blob/47afb25f2863586715307aee17c2fe82f96a5d9e/src/request.ts#L405

Is is possible to improve this function to support date formats (especially Edm.DateTime) ?

You can find all OData v2 primitives Data Types here :
https://www.odata.org/documentation/odata-version-2-0/overview/#ServiceMetadataDocument

Thanks a lot for your help 

BR,

**Comment by Soontao** [comment]
Thank You @tdespres 

I'll check this and update later.

Regards,
Theo

**Comment by Soontao** [comment]
Hi @tdespres 

I've released a beta version (2.19.0-beta.0) for your request, could you try it firstly, and maybe you will have some feedback for this enhancement.

previous, the `id` could be an object with js primitive values.

https://github.com/Soontao/light-odata/blob/be2391851e07b6e2000b4f58cbd2900772e93262/tests/read.v2.spec.ts#L63-L70

in this version I add some new data types which could be used for serialization of Edm.DateTime

* ODataDateTime
* ODataDateTimeOffset
* RawString

https://github.com/Soontao/light-odata/blob/be2391851e07b6e2000b4f58cbd2900772e93262/tests/read.v2.spec.ts#L162-L170

Regards,
Theo

**Comment by tdespres** [comment]
Hello @Soontao,

Very nice but I have some feedback regarding formats : 

- **Edm.DateTime** format should be : `(DateTime=datetime'1995-11-11T00:00:00')`
- **Edm.DateTimeOffset** format should be : `(DateTimeOffset=datetimeoffset’1970-01-01T00:00:00+01:00′)`

BR

**Comment by Soontao** [comment]
Hi @tdespres 

Thanks for your suggestion, please try the version `2.19.0-beta.1`, in that version I removed the `fractional seconds` and `timezone` from `ODataDateTime`. 
but for `ODataDateTimeOffset`, there is no change for that, and I've look at the odata spec and w3c spec, found that the `fractional seconds` is optional for the `DateTimeOffset` type, so that the server should could accept the value of `Edm.DateTimeOffset` with `fractional seconds`, but I still want to get feedback from you, if your server cannot accept that format, maybe I can add a flag on the type.


Regards,
Theo

**Comment by tdespres** [comment]
Hi @Soontao,

`fractional seconds` are accepted by the server so you can leave it like this.
Another remark, a flag could be nice in `ODataDateTime` and `ODataDateTimeOffset` to encode (**encodeURIComponent**) the generated string.
Indeed, by doing some tests, I noticed that the id string is not accepted by the server in batch requests : 
`Content-Type: multipart/mixed; boundary=6b9a9cea-c637-4fbc-b679-f942302ef7bd

--6b9a9cea-c637-4fbc-b679-f942302ef7bd
Content-Type: application/http
Content-Transfer-Encoding: binary

PATCH Entity(StartDate=datetime'2022-01-01T00:00:00',EndDate=datetime'2022-12-31T00:00:00') HTTP/1.1
Accept: application/json
Content-Type: application/json


{"Some":"Data"}

--6b9a9cea-c637-4fbc-b679-f942302ef7bd-`

Should be : 
`Content-Type: multipart/mixed; boundary=6b9a9cea-c637-4fbc-b679-f942302ef7bd

--6b9a9cea-c637-4fbc-b679-f942302ef7bd
Content-Type: application/http
Content-Transfer-Encoding: binary

PATCH Entity(StartDate=datetime'2022-01-01T00%3A00%3A00',EndDate=datetime'2022-12-31T00%3A00%3A00') HTTP/1.1
Accept: application/json
Content-Type: application/json


{"Some":"Data"}

--6b9a9cea-c637-4fbc-b679-f942302ef7bd-`

Thanks for your help,
Regards

**Comment by Soontao** [comment]
hi @tdespres 

Wow, you're using batch, let me have a look at this.

Regards,
THeo

**Comment by tdespres** [comment]
Yeah, of course. Batch is one the most powerful feature of OData. Your package is wonderful because it supports OData v2 au batch requests :)
All that's missing is media management ($value) and the package will be very complete :p

**Comment by Soontao** [comment]
hi @tdespres,

I've released a new version `2.19.0-beta.3`, in that version, the `ODataDateTime` and `ODataDateTimeOffset` will url-encode inner date string by default, and add a flag to disable it. 

a interesting thing is that I found all server implementations i known (SAP Netweaver, SAP CAP, OData.org sample) support the url-encoded format (but also support without url-encoding), so that I set the flag as `true` default, though i dont found any spec to describe that. 

please try the new version, and test it with normal request and batch request. 

have a nice day :)

Regards,
Theo

**Comment by tdespres** [comment]
Hello @Soontao,

Everything is ok !

Thanks a lot,
BR
